
version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  simple-kart-tests:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/10237495-e4f12186-f6d2-4516-80c8-d737c4d402cf?apikey=PMAK-618d6b992cdd810046c2fa0b-30fc7a5967e7ba9bfb11a55e18e5262571 
          environment: https://api.getpostman.com/environments/b9409f0b-70ff-445e-bbbe-649eeb05dc07?apikey=PMAK-618d6b992cdd810046c2fa0b-30fc7a5967e7ba9bfb11a55e18e5262571

workflows:
  example-workflow:
    jobs:
      - simple-kart-tests