version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  simple-kart-tests:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/10237495-ac5e27e2-3fbb-4a85-b86c-804a27d5b64b?apikey=PMAK-618d6b992cdd810046c2fa0b-30fc7a5967e7ba9bfb11a55e18e5262571
          environment: https://api.getpostman.com/environments/10237495-b9409f0b-70ff-445e-bbbe-649eeb05dc07?apikey=PMAK-618d6b992cdd810046c2fa0b-30fc7a5967e7ba9bfb11a55e18e5262571
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  example-workflow:
    jobs:
      - simple-kart-tests
